SET DB = 'EMP';
SET TBL_SCHEMA = 'HRDATA';
SET PROC_SCHEMA = 'PROCS';

USE DATABASE IDENTIFIER($DB);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($PROC_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($TBL_SCHEMA);

USE SCHEMA IDENTIFIER($PROC_SCHEMA);

-- PROCEDURE TO RETURN THE ROW COUNT OF 4 TABLES IN EMP DATABASE  
CREATE OR REPLACE PROCEDURE EMP.PROCS.SP_LITERALS_IDENTIFIERS_DEMO("DBNAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'DEMO PROGRAM ON LITERALS AND IDENTIFIERS'
EXECUTE AS CALLER 
AS

DECLARE
    TABLE1 VARCHAR;
    TABLE2 VARCHAR DEFAULT 'DEPARTMENTS';
    DEPT INTEGER;
    EMPL INTEGER;
    CNTRY INTEGER;
    LOC INTEGER;
BEGIN
    TABLE1 := 'EMPLOYEES';
    LET TABLE3 := 'COUNTRIES';
  --LET TBL_SCHEMA = 'HRDATA';
  
    USE DATABASE IDENTIFIER (:DBNAME);
    USE SCHEMA IDENTIFIER($TBL_SCHEMA);

    SELECT COUNT(*) INTO :EMPL FROM TABLE(:TABLE1);
    SELECT COUNT(*) INTO :DEPT FROM IDENTIFIER(:TABLE2);
    SELECT COUNT(*) INTO :CNTRY FROM TABLE(:TABLE3);
    SELECT COUNT(*) INTO :LOC FROM IDENTIFIER('EMP.HRDATA.LOCATION');

    RETURN 'EMPLOYEES COUNT ' || EMPL || ', DEPARTMENTS COUNT ' || DEPT || ', COUNTRIES COUNT ' || CNTRY || ', LOCATION COUNT ' || LOC;
END;

CALL EMP.PROCS.SP_LITERALS_IDENTIFIERS_DEMO('EMP');
